// packages/metadata-react/src/index.ts
import { useCallback, useMemo, useRef, useState } from 'react';
import {
  createMetadataState,
  getMetadataAttributeValue,
  type CreateMetadataStateOptions,
  type Metadata,
  type MetadataState
} from '@digahash/metadata-core';

interface MetadataSnapshot {
  items: Metadata[];
  isLoading: boolean;
  allLoaded: boolean;
  nextTokenId: number;
  downloadedCount: number;
  groupedItems: Metadata[][];
}

function snapshot(state: MetadataState): MetadataSnapshot {
  return {
    items: [...state.items],
    isLoading: state.isLoading,
    allLoaded: state.allLoaded,
    nextTokenId: state.nextTokenId,
    downloadedCount: state.downloadedCount,
    groupedItems: state.groupedItems
  };
}

export function useMetadata(options: CreateMetadataStateOptions) {
  const stateRef = useRef<MetadataState | null>(null);
  if (!stateRef.current) {
    stateRef.current = createMetadataState(options);
  }

  const state = stateRef.current;
  const [view, setView] = useState<MetadataSnapshot>(() => snapshot(state));

  const sync = useCallback(() => {
    setView(snapshot(state));
  }, [state]);

  const fetchBatch = useCallback(async () => {
    const inFlight = state.fetchBatch();
    sync();
    await inFlight;
    sync();
  }, [state, sync]);

  const fetchAllRemainingMetadata = useCallback(async () => {
    await state.fetchAllRemainingMetadata();
    sync();
  }, [state, sync]);

  const fetchMetadataBatch = useCallback((tokenIds: number[]) => {
    return state.fetchMetadataBatch(tokenIds);
  }, [state]);

  const fetchMetadata = useCallback((tokenId: number) => {
    return state.fetchMetadata(tokenId);
  }, [state]);

  return useMemo(() => ({
    ...view,
    fetchBatch,
    fetchAllRemainingMetadata,
    fetchMetadataBatch,
    fetchMetadata,
    getMetadataAttributeValue
  }), [view, fetchBatch, fetchAllRemainingMetadata, fetchMetadataBatch, fetchMetadata]);
}

export { getMetadataAttributeValue, getPublicAttributeValue, groupItemsIntoRows, fetchSupplyCounts } from '@digahash/metadata-core';
export type {
  CreateMetadataStateOptions,
  Metadata,
  MetadataAttribute,
  MetadataContent,
  UseMetadataOptions
} from '@digahash/metadata-core';

// packages/metadata-angular/src/index.ts
import { Injectable, computed, signal } from '@angular/core';
import {
  createMetadataState,
  getMetadataAttributeValue,
  type CreateMetadataStateOptions,
  type Metadata,
  type MetadataState
} from '@digahash/metadata-core';

@Injectable({ providedIn: 'root' })
export class MetadataService {
  private coreState: MetadataState | null = null;
  private readonly itemsSignal = signal<Metadata[]>([]);
  private readonly isLoadingSignal = signal(false);
  private readonly allLoadedSignal = signal(false);
  private readonly nextTokenIdSignal = signal(0);

  readonly items = computed(() => this.itemsSignal());
  readonly isLoading = computed(() => this.isLoadingSignal());
  readonly allLoaded = computed(() => this.allLoadedSignal());
  readonly nextTokenId = computed(() => this.nextTokenIdSignal());
  readonly downloadedCount = computed(() => this.itemsSignal().length);
  readonly groupedItems = computed(() => (this.coreState ? this.coreState.groupedItems : []));

  initialize(options: CreateMetadataStateOptions): void {
    this.coreState = createMetadataState(options);
    this.sync();
  }

  async fetchBatch(): Promise<void> {
    const coreState = this.getCoreState();
    const inFlight = coreState.fetchBatch();
    this.sync();
    await inFlight;
    this.sync();
  }

  async fetchAllRemainingMetadata(): Promise<void> {
    const coreState = this.getCoreState();
    await coreState.fetchAllRemainingMetadata();
    this.sync();
  }

  fetchMetadataBatch(tokenIds: number[]) {
    const coreState = this.getCoreState();
    return coreState.fetchMetadataBatch(tokenIds);
  }

  fetchMetadata(tokenId: number) {
    const coreState = this.getCoreState();
    return coreState.fetchMetadata(tokenId);
  }

  getMetadataAttributeValue = getMetadataAttributeValue;

  private sync(): void {
    const coreState = this.getCoreState();
    this.itemsSignal.set([...coreState.items]);
    this.isLoadingSignal.set(coreState.isLoading);
    this.allLoadedSignal.set(coreState.allLoaded);
    this.nextTokenIdSignal.set(coreState.nextTokenId);
  }

  private getCoreState(): MetadataState {
    if (!this.coreState) {
      throw new Error('MetadataService is not initialized. Call initialize(options) first.');
    }

    return this.coreState;
  }
}

export function createMetadataService(options: CreateMetadataStateOptions): MetadataState {
  return createMetadataState(options);
}

export { getMetadataAttributeValue, getPublicAttributeValue, groupItemsIntoRows, fetchSupplyCounts } from '@digahash/metadata-core';
export type {
  CreateMetadataStateOptions,
  Metadata,
  MetadataAttribute,
  MetadataContent,
  UseMetadataOptions
} from '@digahash/metadata-core';
